routes/web.php
<?php

use App\Http\Controllers\LivreController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return route('livres.index');
// });

Route::resource('livres',LivreController::class);

app/Models/Categorie.php
<?php

namespace App\Models;

use App\Models\Livre;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Categorie extends Model
{
    use HasFactory;

    protected $fillable = [
        "nom",
        "description"
    ];

    function livres(): HasMany
    {
        return $this->hasMany(Livre::class);
    }

}

app/Models/Livre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Livre extends Model
{
    use HasFactory;

    protected $fillable = [
        "titre",
        "pages",
        "description",
        "categorie_id",
        "image"
    ];

    function categorie():BelongsTo
    {
        return $this->belongsTo(Categorie::class) ;
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/LivreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Livre;
use Illuminate\Http\Request;

class LivreController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $livres = Livre::paginate(20);
        return view('livres.index', compact('livres'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('livres.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'titre' => 'required|string,max:255',
            'pages' => 'required|integer,gt:0',
            'description' => 'required',
            'categorie_id' => 'required',
            'image'=> 'mime:svg,png,jpeg'
        ]);
        if($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("livre/image","public");
            $validateData["image"] = $imagePath;
        }
        return redirect()->route('livre.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $livre = Livre::find($id);
        return view('livre.edit', compact('livre'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->validate([
            'titre' => 'required|string',
            'pages' => 'required|integer',
            'description' => 'required|string',
        ]);

        $livre= Livre::find($id);
        // $livre->update();

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Livre::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>@yield('title')</title>
    <style>
        nav {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: rgb(52, 148, 199);
            padding: 2rem;
            font-size: 1.5rem;
            /* justify-items: space-around; */
        }

        nav div {
            margin: 1.5rem;
        }
    </style>
</head>

<body>
    <nav>
        <div>
            <a class="link" href={{ route('livres.index') }}>Home</a>
        </div>
        {{-- <div><a href="">Edit</a></div> --}}
    </nav>

    @yield('content')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>

resources/views/livres/edit.blade.php
<div>
    <!-- It is not the man who has too little, but the man who craves more, that is poor. - Seneca -->
</div>

resources/views/livres/index.blade.php
@extends('layouts.app')
@section('title','livres')
@section('content')
    <a href={{route('livres.create')}}>Ajouter un livre</a>
<table class="table">
    <thead>
        <th>titre</th>
        <th>pages</th>
        <th>desctiprion</th>
        <th>categorie</th>
        <th colspan="2">Action</th>
    </thead>
    <tbody>
        @foreach ($livres as $livre)
            <tr>
                <td>{{$livre->titre}}</td>
                <td>{{$livre->pages}}</td>
                <td>{{$livre->description}}</td>
                <td>{{$livre->categorie->nom}}</td>
                <td><a href={{route('livres.edit',$livre->id)}} class='btn btn-primary'>editer</a></td>
                <td><a href={{route('livres.destroy',$livre->id)}} class='btn btn-primary'>supprimer</a></td>
            </tr>
        @endforeach

    </tbody>
</table>

@endsection